# Generated by Django 5.2.1 on 2025-05-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Absence')),
                ('justification', models.TextField(blank=True, null=True, verbose_name='Justification')),
                ('classs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_class', to='school.class', verbose_name='Class')),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_matter', to='school.matter', verbose_name='Matter')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_student', to='school.student', verbose_name='Student')),
            ],
            options={
                'unique_together': {('student', 'classs', 'matter', 'date')},
            },
        ),
    ]
