# Generated by Django 5.2.1 on 2025-05-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_absence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_absences', models.PositiveIntegerField(default=0, verbose_name='Total Absences')),
                ('average_grade', models.FloatField(default=0.0, verbose_name='Average Grade')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_card', to='school.student', verbose_name='Student')),
            ],
        ),
    ]
