# Generated by Django 5.2.1 on 2025-05-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_reportcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcard',
            name='average_grade',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='total_absences',
        ),
        migrations.AddField(
            model_name='reportcard',
            name='classs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='school.class'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='grade_final',
            field=models.FloatField(default=0.0, verbose_name='Final Grade'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='matter',
            field=models.ForeignKey(default='1'
            '', on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='school.matter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='school.student'),
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_final', models.FloatField(default=0.0, verbose_name='Final Grade')),
                ('total_absences', models.PositiveIntegerField(default=0, verbose_name='Total Absences')),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history_class', to='school.class', verbose_name='Class')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history_matter', to='school.matter', verbose_name='Matter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='school.student', verbose_name='Student')),
            ],
        ),
    ]
